/* Custom Dark Theme Overrides */
body {
  background-color: #0f111a;
  color: #f5f5f5;
}

h1, h2, h3, h4, h5, h6 {
  color: #00d1ff;
}

a {
  color: #1abfff;
}

a:hover {
  color: #00ffe0;
}

pre, code {
  background-color: #1a1c29;
  color: #ff9d00;
}

blockquote {
  border-left: 4px solid #00d1ff;
  background-color: rgba(0, 209, 255, 0.05);
  color: #a0a0a0;
}

