defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "my-site"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "kubu lee"

      collections:
  my_collection:
    output: true

defaults:
  -
    scope:
      path: "_layouts/home.html"
    values:
      layout: "specific-layout"

